# -*- coding: utf-8 -*-
"""Class06_Home_work.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sUFx17iCOqIYO7YGDkGslkGbddZFuDFm
"""

!pip install numpy pandas matplotlib seaborn

# Import libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from google.colab import drive
import warnings
warnings.filterwarnings('ignore')
gym_membership = pd.read_csv('/content/drive/MyDrive/Dataset/gym_membership.csv')
abonoment_count =gym_membership['abonoment_type'].value_counts()
plt.bar(['Standard', 'Premium'], abonoment_count.values)
plt.title('abonoment_count')
plt.show()

plt.hist(gym_membership['avg_time_in_gym'])
plt.title('avg_time_in_gym')
plt.show()

gym=gym_membership.head(100)
plt.scatter(gym_membership['Age'], gym_membership['visit_per_week'])
plt.grid(True)
plt.xlabel('Age')
plt.ylabel('visit_per_week')
plt.title('Age vs visit_per_week')
plt.show()

sns.boxplot(data=gym_membership, x='gender', y='Age')
plt.grid(True, which="both", linestyle="--", linewidth=0.7, alpha=0.7)
plt.title('Age by Gender')
plt.show()
sns.countplot(data=gym_membership, x='days_per_week')
plt.grid(True,which="both",linestyle="--", linewidth=0.7, alpha=0.7)
plt.title('days_per_week')
plt.show()
sns.barplot(data=gym_membership, x='abonoment_type', y='visit_per_week')
plt.grid(True,which="both",linestyle="--", linewidth=0.7, alpha=0.7)
plt.title('abdominals vs visit_per_week')
plt.show()